# Generated by Django 2.1 on 2018-10-28 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_detail',
            fields=[
                ('attendance_detail_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entry_datetime', models.DateTimeField(blank=True, null=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.Attendance')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_no', models.IntegerField()),
                ('attdate', models.DateField()),
                ('atttime', models.TimeField()),
                ('verifytime', models.DateTimeField()),
                ('deviceid', models.IntegerField()),
                ('remarks', models.CharField(max_length=255)),
                ('attmode', models.IntegerField(default=0)),
                ('verifytype', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroom_id', models.AutoField(primary_key=True, serialize=False)),
                ('classroom_name', models.CharField(max_length=55)),
                ('block', models.CharField(max_length=55)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('deviceid', models.IntegerField(primary_key=True, serialize=False)),
                ('devicename', models.CharField(max_length=100)),
                ('deviceip', models.CharField(default='0.0.0.0', max_length=50)),
                ('devicekey', models.CharField(max_length=255, unique=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.AutoField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='Faculty_Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_no', models.IntegerField()),
                ('fingerprint', models.TextField()),
                ('finger_number', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Fingerprints',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('year', models.CharField(max_length=5)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Group_Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('module_code', models.CharField(blank=True, max_length=10, null=True)),
                ('period', models.CharField(blank=True, max_length=20)),
                ('level', models.CharField(max_length=25)),
                ('credit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('routine_id', models.AutoField(primary_key=True, serialize=False)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('day_of_the_week', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default='', max_length=10)),
                ('class_type', models.CharField(choices=[('Lecture', 'Lecture'), ('Tutorial', 'Tutorial'), ('Lab', 'Lab')], default='', max_length=15)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.Classroom')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('student_first_name', models.CharField(max_length=50)),
                ('student_last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact', models.CharField(blank=True, max_length=15)),
                ('current_address', models.CharField(blank=True, max_length=95)),
                ('permanent_address', models.CharField(blank=True, max_length=95)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_no', models.IntegerField(unique=True)),
                ('effective_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Student_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.Group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Student_module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.Module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('firstname', models.CharField(default='', max_length=50)),
                ('lastname', models.CharField(default='', max_length=50)),
                ('teacher_type', models.CharField(choices=[('Lecturer', 'Lecturer'), ('Tutor', 'Tutor')], default='', max_length=10)),
                ('username', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(choices=[('Lecture', 'Lecture'), ('Tutorial', 'Tutorial'), ('Lab', 'Lab'), ('Tutorial and Lab', 'Tutorial and Lab')], default='', max_length=20)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.Module')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='routine',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.Teacher'),
        ),
        migrations.AddField(
            model_name='group_routine',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.Routine'),
        ),
        migrations.AddField(
            model_name='faculty_module',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.Module'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='devicekey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Attendance.Device', to_field='devicekey'),
        ),
        migrations.AddField(
            model_name='attendance_detail',
            name='device_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Attendance.Device'),
        ),
        migrations.AddField(
            model_name='attendance_detail',
            name='enroll_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Attendance.Student_Enrollment', to_field='enroll_no'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.Classroom'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.Routine'),
        ),
    ]
