# Generated by Django 2.1 on 2018-10-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_detail',
            name='device_id',
        ),
        migrations.AlterField(
            model_name='device',
            name='deviceip',
            field=models.CharField(max_length=50),
        ),
    ]
