# Generated by Django 2.1 on 2018-10-29 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0003_auto_20181029_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_enrollment',
            old_name='enroll_no',
            new_name='enrollno',
        ),
    ]
