# Generated by Django 2.1 on 2018-10-29 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0004_auto_20181029_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_enrollment',
            old_name='enrollno',
            new_name='enroll_no',
        ),
        migrations.AlterField(
            model_name='attendance_detail',
            name='enrollno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='devicekey',
            field=models.ForeignKey(blank=True, db_column='devicekey', null=True, on_delete=django.db.models.deletion.CASCADE, to='Attendance.Device', to_field='devicekey'),
        ),
    ]
