# Generated by Django 2.1 on 2018-10-29 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0006_auto_20181029_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_detail',
            name='enrollno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Attendance.Student_Enrollment', to_field='enrollno'),
        ),
    ]
