# Generated by Django 2.1 on 2018-10-29 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0008_auto_20181029_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='classroom',
            field=models.ForeignKey(db_column='classroom', on_delete=django.db.models.deletion.CASCADE, to='Attendance.Classroom'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='routine',
            field=models.ForeignKey(db_column='routine', on_delete=django.db.models.deletion.CASCADE, to='Attendance.Routine'),
        ),
    ]
