# Generated by Django 2.1 on 2018-10-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0009_auto_20181029_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='deviceid',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='remarks',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='verifytime',
            field=models.DateTimeField(blank=True),
        ),
    ]
