# Generated by Django 2.1 on 2018-10-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0010_auto_20181029_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='deviceid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='verifytime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
