# Generated by Django 2.1 on 2018-10-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0011_auto_20181029_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
