# Generated by Django 2.1 on 2018-10-31 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0012_routine_startdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='level',
            new_name='year',
        ),
    ]
