# Generated by Django 2.1 on 2018-11-14 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0013_auto_20181031_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_detail',
            name='devicekey',
            field=models.ForeignKey(blank=True, db_column='devicekey', null=True, on_delete=django.db.models.deletion.CASCADE, to='Attendance.Device', to_field='devicekey'),
        ),
    ]
